// Type definition for abbreviation items
type AbbreviationItem = {
  acronym: string;
  fullForm: string;
  explanation?: string;
  reference?: string;
};

export const abbreviations: Record<string, AbbreviationItem[]> = {
  A: [
    {
      acronym: "AAWS",
      fullForm: "Advanced Approach Warning System",
      explanation:
        "A system that warns drivers of an approaching train before they enter the track.",
      reference: "--",
    },
    { acronym: "ACD", fullForm: "Anti Collision Device" },
    { acronym: "ACMS", fullForm: "Additional Chief Medical Superintendent" },
    { acronym: "ACP", fullForm: "Alarm Chain Pulling" },
    { acronym: "ACPCNF", fullForm: "Alarm Chain Pulled But Culprit Not Found" },
    { acronym: "ADCR", fullForm: "Analog to Digital Converter Relay" },
    { acronym: "ADGM", fullForm: "Additional Deputy General Manager" },
    { acronym: "ADMO", fullForm: "Assistant Divisional Medical Officer" },
    { acronym: "ADRM", fullForm: "Additional Divisional Railway Manager" },
    { acronym: "AEN", fullForm: "Assistant Engineer" },
    { acronym: "AFM", fullForm: "Assistant Finance Manager" },
    {
      acronym: "AFRES",
      fullForm: "Advanced Finance & Railway Earning & Expenditure System",
    },
    { acronym: "AFTO", fullForm: "Automobile Frieght Train Operators" },
    { acronym: "AGM", fullForm: "Additional General Manager" },
    { acronym: "AIMS", fullForm: "Accounting Information Management System" },
    { acronym: "AIRF", fullForm: "All India Railwaymen’s Federation" },
    { acronym: "AISMA", fullForm: "All India Station Masters Association" },
    { acronym: "AITUC", fullForm: "All India Trade Union Congress" },
    { acronym: "AMA", fullForm: "Authorised Medical Attendant" },
    { acronym: "AME", fullForm: "Assistant Mechanical Engineer" },
    { acronym: "AOM", fullForm: "Assistant Operations Manager" },
    { acronym: "APAR", fullForm: "Annual Performance Appraisal Report" },
    { acronym: "APO", fullForm: "Assistant Personnel Officer" },
    { acronym: "ARME", fullForm: "Accident Relief Medical Equipment" },
    { acronym: "ARMS", fullForm: "Accounting Reforms Management System" },
    { acronym: "ARMV", fullForm: "Accident Relief Medical Van" },
    { acronym: "ARPAN", fullForm: "Advanced Railway Pension Access Network" },
    { acronym: "ARRI", fullForm: "Automatic Route Relay Interlocking" },
    { acronym: "ARS", fullForm: "All Right Signal" },
    { acronym: "ART", fullForm: "Accident Relief Train" },
    { acronym: "ASAR", fullForm: "As Soon As Ready" },
    { acronym: "ASI", fullForm: "Approved Special Instructions" },
    { acronym: "ASS", fullForm: "Automatic Stop Signal" },
    { acronym: "ATLC", fullForm: "Assistant Traction Loco Controller" },
    { acronym: "ATM", fullForm: "Assistnat Transportation Manager" },
    { acronym: "ATP", fullForm: "Authority To Proceed" },
    { acronym: "ATVM", fullForm: "Automatic Ticket Vending Machine" },
    { acronym: "AWS", fullForm: "Auxillary Warning System" },
    { acronym: "AYS", fullForm: "Assistant Yard Master" },
  ],
  B: [
    { acronym: "BAL", fullForm: "Brake Applied Loop" },
    { acronym: "BAS", fullForm: "Biometric Attendance System" },
    { acronym: "BCB", fullForm: "Bell Code Button" },
    { acronym: "BCL", 
      fullForm: "Braithwaite & Co. Limited",
      explanation: "To manufacture Wagons, undertake structural fabrication jobs and manufacturing, retrofitting of EOT crane.",
      reference: "--"
     },
    { acronym: "BCM", fullForm: "Ballast Cleaning Machine" },
    { acronym: "BCU", fullForm: "Brake Control Unit" },
    { acronym: "BIC", fullForm: "Bogie Isolation Cock" },
    { acronym: "BMBS", fullForm: "Bogie Mounted Brake System" },
    { acronym: "BOBYN", fullForm: "Bogie Open Hopper Wagon Bottom Discharge" },
    { acronym: "BCXR", fullForm: "Bogie Wagon Covered with Screw Coupling" },
    { acronym: "BCXC", fullForm: "Bogie Wagon Covered with CBC Coupling" },
    {
      acronym: "BCXT",
      fullForm: "Bogie Wagon Covered with Transitional Coupling",
    },
    { acronym: "BCN", fullForm: "Bogie Wagon Covered with Air Brake & CTC" },
    {
      acronym: "BCNA",
      fullForm: "Bogie Wagon Covered Arrangement for Improved",
    },
    { acronym: "BEML", fullForm: "Bharat Earth Movers Limited", explanation: "To manufacture construction and mining equipment.", reference: "--" },
    { acronym: "BFR", fullForm: "Bogie Flat for Rail (Vaccuum Brake)" },
    { acronym: "BFK", fullForm: "Bogie Flat Container Car" },
    { acronym: "BFU", fullForm: "Bogie Well Wagon" },
    { acronym: "BKH", fullForm: "Bogie Open Hopper Wagon (Side Discharge)" },
    { acronym: "BLW", fullForm: "Baldwin Locomotive Works", explanation: "To manufacture locomotives.", reference: "--" },
    { acronym: "BOBR", fullForm: "Breach Of Block Rules" },
    { acronym: "BOBRN", fullForm: "Bogie Open Bottom Rapid Dischrge with Pneumatic Brake" },
    { acronym: "BOBSN", fullForm: "Bogie Hopper Wagon Bottom side Discharge with Pneumatic Brake" },
    { acronym: "BOL", fullForm: "Block Over Lap" },
    { acronym: "BOMN", fullForm: "Bogie Open Wagon for Military Loading with Pneumatic Brake" },
    { acronym: "BOST", fullForm: "Bogie Open for Steel with Air Brake & CBC" },
    { acronym: "BOXNR", fullForm: "Bogie Open Wagon Air Brake Rehabilitation" },
    { acronym: "BOXNHA", fullForm: "Bogie Open with Air Brake High Axle Load" },
    {
      acronym: "BOXNHS",
      fullForm: "Bogie Open with Air Brake High Speed (CBC)",
    },
    {
      acronym: "BOXNHSM1",
      fullForm: "Bogie Open with Air Brake High Speed Modified 1",
    },
    { acronym: "BOXNAL", fullForm: "Bogie Open with Air Brake Aluminium Body" },
    { acronym: "BOXNEL", fullForm: "Bogie Open with Air Brake Loaded" },
    { acronym: "BOXR", fullForm: "Bogie Open with Screw Coupling" },
    { acronym: "BOXC", fullForm: "Bogie Open with CBC Coupling" },
    { acronym: "BOXT", fullForm: "Bogie Open with Transitional Coupling" },
    { acronym: "BOXN", fullForm: "Bogie Open for Coal with Air Brake & CBC" },
    {
      acronym: "BOXMN1",
      fullForm: "Bogie Open Air Brake Light Weight Modified 1",
    },
    { acronym: "BOYN", fullForm: "Bogie Open Wagon for Ores Loading with Pneumatic Brake" },
    { acronym: "BPAC", fullForm: "Block Proving by Axle Counter" },
    { acronym: "BPC", fullForm: "Brake Power Certificate" },
    { acronym: "BPT", fullForm: "Blank Paper Ticket" },
    { acronym: "BRH", fullForm: "Bogie Flat for Rail (Roller Bearing)" },
    { acronym: "BRM", fullForm: "Ballast Regulating Machine" },
    { acronym: "BRN", fullForm: "Bogie Flat for Rail (Air Brake)" },
    { acronym: "BRNA", fullForm: "Bogie Rail Truck Air" },
    { acronym: "BRNAHS", fullForm: "Bogie Rail Truck Air High Speed" },
    { acronym: "BSCL", 
      fullForm: "Burn Standard Company Limited", 
      explanation: "To manufacture Railway Rolling Stock.", 
      reference: "--" 
    },
    { acronym: "BSLB", fullForm: "Block Section Limit Board" },
    { acronym: "BTPN", fullForm: "Bogie Tank Wagon for Petrol (Air Brake)" },
    { acronym: "BTPGL", fullForm: "Bogie Tank Wagon for LPG (Vaccum Brake)" },
    { acronym: "BTPGLN", fullForm: "Bogie Tank Wagon for LPG (Air Brake)" },
    { acronym: "BCGT", fullForm: "Brake Van Goods with Transitional Coupling" },
    {
      acronym: "BVGC",
      fullForm: "Brake Van Goods with CBC Coupling 4 Wheeler (Air Brake)",
    },
    { acronym: "BUD", fullForm: "Basic User Data" },
    { acronym: "BWEL", 
      fullForm: "Bharat Wagon & Engineering Limited", 
      explanation: "To manufacture Wagons and undertake structural fabrication jobs.", 
      reference: "--" 
    },
    { acronym: "BUZC", fullForm: "4 Wheeler Brake Van" },
    { acronym: "BUZI", fullForm: "8 Wheeler Brake Van" },
    { acronym: "BWL", fullForm: "Bogie Well Wagon" },
    { acronym: "BWM", fullForm: "Block Working Manual" },
  ],
  C: [
    { acronym: "CADAT", fullForm: "Computer Aided Drivers Aptitude Test" },
    {
      acronym: "CAMTECH",
      fullForm: "Centre for Advanced Maintenance Technology.",
    },
    { acronym: "CAO", fullForm: "Chief Accounts Officer" },
    { acronym: "CAO", fullForm: "Chief Administrative Officer" },
    { acronym: "CAT", fullForm: "Central Administrative Tribunal" },
    { acronym: "CB", fullForm: "Caution Board" },
    { acronym: "CBC", fullForm: "Central Buffer Coupler" },
    { acronym: "CBS", fullForm: "Chief Booking Supervisor" },
    {
      acronym: "CBTC",
      fullForm: "Communication based train control technology",
    },
    { acronym: "CBTC", fullForm: "Chief Ballast Train Controller" },
    { acronym: "CC", fullForm: "Carrying Capacity" },
    { acronym: "CCC", fullForm: "Chief Crew Controller" },
    { acronym: "CCI", fullForm: "Container Corporation of India" },
    { acronym: "CCL", fullForm: "Child Care Leave" },
    { acronym: "CCM", fullForm: "Chief Commercial Manager" },
    { acronym: "CCO", fullForm: "Chief Claims Officer" },
    { acronym: "CCRS", fullForm: "Chief Commissioner Railway Safety" },
    { acronym: "CDTS", fullForm: "Control Discharge Toilet System" },
    { acronym: "CDU", fullForm: "Cab Display unit" },
    { acronym: "CEE", fullForm: "Chief Electrical Engineer" },
    { acronym: "CE", fullForm: "Couple Engine" },
    { acronym: "CELE", fullForm: "Chief Electrical Locomotive Engineer" },
    { acronym: "CELE", fullForm: "Coupled Electric Light Engine" },
    { acronym: "CFTM", fullForm: "Chief Freight Transportation Manager" },
    {
      acronym: "CGEGIS",
      fullForm: "Central Government Employee Group Insurance Scheme",
    },
    { acronym: "CHC", fullForm: "Chief Controller" },
    { acronym: "CI", fullForm: "Catution Indicator" },
    { acronym: "CLAP", fullForm: "Comprehensive Logistics Action Plan" },
    { acronym: "CLCT", fullForm: "Conditional Line Clear Ticket" },
    { acronym: "CLE", fullForm: "Chief Locomotive Engineer" },
    { acronym: "CLI", fullForm: "Chief Loco Inspector" },
    { acronym: "CLW", fullForm: "Chittaranjan Locomotive Works" },
    { acronym: "CMD", fullForm: "Chief Medical Director" },
    { acronym: "CME", fullForm: "Chief Mechanical Engineer" },
    { acronym: "CMI", fullForm: "Chief Mechanical Inspector" },
    { acronym: "CMM", fullForm: "Coaching Maintenance Management" },
    { acronym: "CMO", fullForm: "Cheif Medical Officer" },
    { acronym: "CMPE", fullForm: "Chief Motive Power Engineer" },
    { acronym: "CMS", fullForm: "Crew Management System" },
    { acronym: "CMS", fullForm: "Chief Medical Superintendent" },
    { acronym: "CMRL", fullForm: "Cennai Rail Metro Limited" },
    { acronym: "CO", fullForm: "Caution Order" },
    { acronym: "COA", fullForm: "Control Office Application" },
    { acronym: "COATVM", fullForm: "Cash/Cum Coin And Smart Card Operated Ticket Vending Machine" },
    { acronym: "COFMOW", fullForm: "Central Organization For Modernization Of Workshop" },
    { acronym: "COS", fullForm: "Controller of Stores" },
    { acronym: "COIS", fullForm: "Coaching Operations Information System" },
    { acronym: "COM", fullForm: "Chief Operations Manager" },
    { acronym: "COMS", fullForm: "Complaint Management System" },
    { acronym: "CONCOR", 
      fullForm: "Container Corporation of India Limited",
      explanation: "To develop multi-modal logistics support for India’s international and domestic containerized cargo and trade.",
      reference: "--"
    },
    {
      acronym: "CORE",
      fullForm: "Central Organization for Railway Electrification",
    },
    { acronym: "COTVM", fullForm: "Currency Operated Ticket Vending Machine" },
    { acronym: "CPC", fullForm: "Central Pay Commission" },
    { acronym: "CPGO", fullForm: "Chief Public Grievance Officer" },
    {
      acronym: "CPGRAMS",
      fullForm: "Centralized Public Grievance Redress And Monitoring System",
    },
    { acronym: "CPM", fullForm: "Chief Project Manager" },
    { acronym: "CPRO", fullForm: "Chief Public Relations Officer" },
    { acronym: "CPTM", fullForm: "Chief Passenger Transportation Manager" },
    { acronym: "CRB", fullForm: "Chairman of Railway Board" },
    { acronym: "CRIS", fullForm: "Centre for Railway Information System", explanation: "To provide consultancy and IT services to IR as partners to conceptualize and realize technology initiatives, to build new products or services and to implement prudent business and technology strategies.", reference: "--" },
    { acronym: "CRRM", fullForm: "Credit from Rail Release Material" },
    { acronym: "CRS", fullForm: "Commissioner of Railway Safety" },
    { acronym: "CRSE", fullForm: "Chief Rolling Stock Engineer" },
    { acronym: "CRT", fullForm: "Container Rail Terminal" },
    { acronym: "CSO", fullForm: "Chief Safety Officer" },
    { acronym: "CSO", fullForm: "Central Standards Office" },
    { acronym: "CSTE", fullForm: "Chief Signal & Telecommunication Engineer" },
    { acronym: "CTARA", fullForm: "Centralized Training Academy for Railway Accounts" },
    { acronym: "CTC", fullForm: "Centralized Traffic Control" },
    { acronym: "CTI", fullForm: "Centralised Training Institutes" },
    { acronym: "CTLC", fullForm: "Chief Train Loco Controller" },
    { acronym: "CTNC", fullForm: "Chief Train Clerk" },
    { acronym: "CTO", fullForm: "Container Train Operators" },
    { acronym: "CTPC", fullForm: "Chief Traction Power Controller" },
    { acronym: "CTR", fullForm: "Combined Train Report" },
    { acronym: "CTR", fullForm: "Complete Track Renewal" },
    { acronym: "CVO", fullForm: "Chief Vigilance Officer" },
    { acronym: "CUG", fullForm: "Closed User Group" },
    { acronym: "CWC", fullForm: "Carriage & Wagon Controller" },
    { acronym: "CWE", fullForm: "Chief Workshop Engineer" },
    { acronym: "CWM", fullForm: "Chief Workshop Manager" },
    { acronym: "CWR", fullForm: "Continuous Welded Rails" },
  ],
  D: [
    { acronym: "DAC", fullForm: "Digital Axle Counter" },
    { acronym: "DAO", fullForm: "Divisional Accounts Officer" },
    { acronym: "DAR", fullForm: "Discipline & Appeal Rules" },
    { acronym: "DCM", fullForm: "Divisional Commercial Manager" },
    { acronym: "DCO", fullForm: "Divisional Caution Order" },
    { acronym: "DCOS", fullForm: "Divisional Controller Of Stores" },
    { acronym: "DCP", fullForm: "Duty Card Pass" },
    { acronym: "DCPT", fullForm: "Digital Capacity Planning Tool" },
    { acronym: "DCRG", fullForm: "Death Cum Retirement Gratuity" },
    { acronym: "DDC", fullForm: "Department Dealing Clerks" },
    { acronym: "DDU", fullForm: "Driver Display Unit" },
    { acronym: "DEE", fullForm: "Divisional Electrical Engineer" },
    { acronym: "DEMU", fullForm: "Diesel Electrical Multiple Unit" },
    { acronym: "DEN", fullForm: "Divisional Engineer" },
    { acronym: "DFC", fullForm: "Dedicated Freight Corridor" },
    {
      acronym: "DFCCIL",
      fullForm: "Dedicated Freight Corridor Corporation of India Limited",
      explanation: "To plan and construct Dedicated Rail Freight Corridors (DFCs) for movement of freight trains on the corridors.",
      reference: "--"
    },
    { acronym: "DFM", fullForm: "Divisional Finance Manager" },
    { acronym: "DGM", fullForm: "Deputy General Manager" },
    { acronym: "DLBI", fullForm: "Double Line Block Instrument" },
    { acronym: "DLE", fullForm: "Diesel Light Engine" },
    { acronym: "DME", fullForm: "Divisional Mechanical Engineer" },
    { acronym: "DMI", fullForm: "Driver Machine Interface" },
    { acronym: "DMM", fullForm: "Divisional Material Manager" },
    { acronym: "DMO", fullForm: "Divisional Medical Officer" },
    { acronym: "DMRC", fullForm: "Delhi Metro Rail Corporation" },
    { acronym: "DMT", fullForm: "Departmental Material Trains" },
    { acronym: "DMU", fullForm: "Diesel Multiple Unit" },
    { acronym: "DOM", fullForm: "Divisional Operating Manager" },
    { acronym: "DPC", fullForm: "Diesel Power Controller" },
    { acronym: "DPC", fullForm: "Divisional Power Control" },
    { acronym: "DPO", fullForm: "Divisional Personnel Officer" },
    { acronym: "DPR", fullForm: "Detailed Project Report" },
    { acronym: "DRF", fullForm: "Depreciation Reserve Fund" },
    { acronym: "DRM", fullForm: "Divisional Railway Manager" },
    { acronym: "DRS", fullForm: "Deficiency Rolling Stock" },
    { acronym: "DRS", fullForm: "Departmental Review System" },
    {
      acronym: "DRUCC",
      fullForm: "Divisional Railway Users Consultative Committee",
    },
    { acronym: "DS", fullForm: "Derailing Switch" },
    { acronym: "DSC", fullForm: "Divisional Safety Commissoner" },
    { acronym: "DSC", fullForm: "Digital Signature Certificate" },
    { acronym: "DSO", fullForm: "Divisional Safety Officer" },
    {
      acronym: "DSTE",
      fullForm: "Divisional Signal & Telecommunication Engineer",
    },
    { acronym: "DTI", fullForm: "Divisional Traffic Inspector" },
    { acronym: "DTTC", fullForm: "Divisional Transportation Training Center" },
  ],
  E: [
    { acronym: "EA", fullForm: "Extra Allowances" },
    { acronym: "EACT", fullForm: "Electronic Allotment for Congested Terminals" },
    { acronym: "EBD", fullForm: "Emergency Braking Distance" },
    { acronym: "EBL", fullForm: "Emergency Brake Loop" },
    { acronym: "EBR", fullForm: "Extra Budgetary Resources" },
    { acronym: "ECA", fullForm: "Employees Compensation Act" },
    { acronym: "ECRC", fullForm: "Enquiry Cum Reservation Clerk" },
    { acronym: "e-DAS", fullForm: "Electronic Drawing Approval System" },
    { acronym: "EDD", fullForm: "Early Departure Detention" },
    { acronym: "EECH", fullForm: "Extreme Emergency Crank Handle" },
    { acronym: "EFT", fullForm: "Excess Fare Ticket" },
    { acronym: "EFT", fullForm: "Emergency Field Telephone" },
    { acronym: "EIMWB", fullForm: "Electronic In - Motion Weigh Bridge" },
    { acronym: "EIRR", fullForm: "Economic Internal Rate of Return" },
    { acronym: "EKT", fullForm: "Electronic Key Transmitter" },
    { acronym: "EMD", fullForm: "Employee Master Data" },
    { acronym: "EMD", fullForm: "Electro Motive Diesel" },
    { acronym: "EMU", fullForm: "Electric Multiple Unit" },
    { acronym: "EOG", fullForm: "End On Generator" },
    { acronym: "EOL", fullForm: "Engine On Load" },
    { acronym: "EOT", fullForm: "Engine On Train" },
    { acronym: "EOTT", fullForm: "End of Train Telemetry" },
    { acronym: "EPB", fullForm: "Emergency Power Block" },
    { acronym: "EPS", fullForm: "E-Procurement System" },
    { acronym: "ESP", fullForm: "Engineering Scale Plan" },
    { acronym: "ES", fullForm: "Elementary Section" },
    {
      acronym: "ESS",
      fullForm: "Employee Self Service & Internal Applications",
    },
    { acronym: "ETRR", fullForm: "Electronic Transmission of Railway Receipt" },
    { acronym: "EWSS", fullForm: "E-Working Software Solution" },
  ],
  F: [
    { acronym: "FEMA", fullForm: "Failure Mode & Effects Analysis" },
    { acronym: "FIBA", fullForm: "Failure Indication and Brake Application" },
    { acronym: "FIRR", fullForm: "Financial Internal Rate of Return" },
    { acronym: "FL", fullForm: "Flasher Light" },
    { acronym: "FM", fullForm: "Fouling Mark" },
    { acronym: "FMVFT", fullForm: "Frequency Modulated Voice Frequency Telegraph" },
    { acronym: "FNM", fullForm: "Fort-Nightly Meetings" },
    { acronym: "FNR", fullForm: "Freight Name Record" },
    { acronym: "FOIS", fullForm: "Freight Operations & Information System" },
    { acronym: "FRED", fullForm: "Flashing Rear End Device" },
    { acronym: "FSD", fullForm: "Fag Safe Device" },
    { acronym: "FSS", fullForm: "First Stop Signal" },
    { acronym: "FTCB", fullForm: "Fixed Time Corridor Block" },
    { acronym: "FTR", fullForm: "Full Tariff Rate" },
    { acronym: "FWP", fullForm: "Final Works Program" },
    { acronym: "FWU", fullForm: "Final Works Program" },
  ],
  G: [
    { acronym: "GAGAN", fullForm: "GPS aided GEO augmented Navigation" },
    { acronym: "GCT", fullForm: "Gati Shakti Multi-Modal Cargo Terminal" },
    { acronym: "GDC", fullForm: "Grievance Dealing Clerk" },
    { acronym: "GDCE", fullForm: "General Departmental Competitive Exam" },
    { acronym: "GDR", fullForm: "Guard Driver Check Report" },
    { acronym: "GeM", fullForm: "Government e - Market" },
    { acronym: "GIO", fullForm: "Grievance In-Charge Officer" },
    { acronym: "GIPR", fullForm: "Great Indian Penisular Railway" },
    { acronym: "GIS", fullForm: "Group Incentive Scheme" },
    { acronym: "GM", fullForm: "General Manager" },
    { acronym: "GOB", fullForm: "General Order Book" },
    { acronym: "GR", fullForm: "General Rules" },
    { acronym: "GRP", fullForm: "Government Railway Police" },
    { acronym: "GRRC", fullForm: "General Rules Review Committee" },
    { acronym: "GS", fullForm: "Ordinary Second Class" },
    { acronym: "GSCN", fullForm: "Generation Second Class Three Tier AC" },
    { acronym: "GSD", fullForm: "General Stores Department" },
    { acronym: "GTA", fullForm: "Goods Transporation Agency" },
    { acronym: "GTKM", fullForm: "Gross Tonne Kilo Meter" },
    { acronym: "GWB", fullForm: "Goods Warning Board" },
    { acronym: "GWI", fullForm: "Grievance Welfare Inspector" },
    { acronym: "GWR", fullForm: "Gate Working Rules" },
  ],
  H: [
    { acronym: "HKT", fullForm: "Happer Key Transmitter" },
    { acronym: "HMIS", fullForm: "Hospital Management Information System" },
    { acronym: "HRMS", fullForm: "Human Resource Management System" },
    {
      acronym: "HOER",
      fullForm:
        "Hours Of Employment and Period of Rest",
    },
    { acronym: "HOG", fullForm: "Head On Generation" },
    { acronym: "HOR", fullForm: "High Official Requisition" },
    { acronym: "HSN", fullForm: "Harmonised System of Nomenclature" },
    { acronym: "HSRC", 
      fullForm: "High Speed Rail Corporation of India", 
      explanation: "For development and implementation of high speed rail projects.", 
      reference: "--  " 
    },
    { acronym: "HSRI", fullForm: "High Speed Rail Coroporation of India Limited" },
  ],
  I: [
    { acronym: "IBH", fullForm: "Intermediate Block Hut" },
    { acronym: "IBP", fullForm: "Intermediate Block Post" },
    { acronym: "IBS", fullForm: "Intermediate Block Signalling" },
    { acronym: "IBSS", fullForm: "Intermediate Block Stop Signal" },
    { acronym: "ICD", fullForm: "Inland Container Deports" },
    { acronym: "ICF", fullForm: "IIntegrated Coach Factory" },
    { acronym: "ICMS", fullForm: "Integrated Coaching Management Systems" },
    {
      acronym: "ICRTS",
      fullForm: "Integrated Computerized Reservation & Ticketing System",
    },
    { acronym: "IDS", fullForm: "Integration of Digital System" },
    { acronym: "IDS", fullForm: "Inner Distant Signal" },
    { acronym: "IMR", fullForm: "Immediate Rail Renewal" },
    { acronym: "INRWF", fullForm: "Indian National Railway Workers’ Federation" },
    { acronym: "INTUC", fullForm: "Indian National Trade Union Congress" },
    { acronym: "IOH", fullForm: "Intermediate Over Hauling" },
    { acronym: "IOL", fullForm: "Intra Ocular Lens" },
    { acronym: "IOP", fullForm: "Inoperatvie Piston" },
    { acronym: "IOW", fullForm: "Inspector of Works" },
    { acronym: "IPAS", fullForm: "Integrated Payroll and Accounting System" },
    { acronym: "IPMD", fullForm: "Infrastructure Projects Monitoring Device" },
    { acronym: "IPWE", fullForm: "Institution of Permanent Way Engineers" },
    { acronym: "IRAS", fullForm: "Indian Railway Accounts Service" },
    { acronym: "IRCA", fullForm: "Indian Railway Conference Association" },
    { acronym: "IRCON", fullForm: "Indian Railway Construction Corporation", 
      explanation: "To undertake construction activities in India and abroad on turnkey basis or otherwise in various fields of infrastructure like Railways, Bridges, Roads, Highways, Industrial and Residential Complexes, Airports, etc.", 
      reference: "--" 
    },
    {
      acronym: "IRCTC",
      fullForm: "Indian Railway Categoring & Tourism Corporation Limited",
      explanation: "To undertake catering and tourism activities of the Railways. Also facilitates internet ticketing through its website.",
      reference: "--"
    },
    { acronym: "IREM", fullForm: "Indian Railway Establishment Manual" },
    { acronym: "IREPS", fullForm: "Indian Railway Electronic Procurement System" },
    { acronym: "IRFC", 
      fullForm: "Indian Railway Finance corporation",
      explanation: "To raise funds from the market to part finance the Plan Outlay of IR.",
      reference: "--"
    },
    { acronym: "IRCEN", fullForm: "Indian Railways Institute of Civil Engineering" },
    { acronym: "IRHS", fullForm: "Indian Railway Health Services" },
    { acronym: "IRICEN", fullForm: "Indian Railway Institute of Civil Engineering" },
    { acronym: "IRPFS", fullForm: "Indian Railways Protection Force Services" },
    { acronym: "IRIEEN", fullForm: "Indian Railways Institute of Electrical Engineering" },
    { acronym: "IRIFM", fullForm: "Indian Railways Institute of Financial Management" },
    { acronym: "IRILMM", fullForm: "Indian Railways Institute of Logistics & Materials Management" },
    { acronym: "IRIMEE", fullForm: "Indian Railways Institute of Mechanical and Electrical Engineering" },
    { acronym: "IRISET", fullForm: "Indian Railways Institute of Signal Engineering and Telecommunications" },
    { acronym: "IRITM", fullForm: "Indian Railways Institute of Transport Management" },
    {
      acronym: "IRLDA",
      fullForm: "Indian Railways Land Development Authority",
    },
    { acronym: "IRMM", fullForm: "Indian Railway Medical Manual" },
    { acronym: "IRMS", fullForm: "Indian Railway Medical Service" },
    { acronym: "IRMS", fullForm: "Indian Railway Management Service" },
    { acronym: "IRPS", fullForm: "Indian Railway Personnel Service" },
    {
      acronym: "IRPSM",
      fullForm: "Indian Railway Projects & Sanctioning Management",
    },
    { acronym: "IRPWM", fullForm: "Indian Railways Permanent Way Manual" },
    { acronym: "IRSDC", fullForm: "Indian Railway Station Development Corporation" },
    { acronym: "IRSE", fullForm: "Indian Railway Service of Engineers" },
    {
      acronym: "IRSEE",
      fullForm: "Indian Railway Service of Electrical Engineers",
    },
    { acronym: "IRSEM", fullForm: "Indian Railways Signal Engineering Manual" },
    {
      acronym: "IRSME",
      fullForm: "Indian Railway Service of Mechanical Engineers",
    },
    { acronym: "IRSS", fullForm: "Indian Railway Stores Service" },
    {
      acronym: "IRSSE",
      fullForm: "Indian Railway Service of Signal Engineers",
    },
    { acronym: "IRST", fullForm: "Inter Section Running Time" },
    { acronym: "IRTMM", 
      fullForm: "Indian Railway Track Machine Manual",
      explanation: "To provide track maintenance and repair services to the Indian Railways.",
      reference: "IRTMM - 2019"
    },
    { acronym: "IRTRD", fullForm: "Implementation of Regulatory in Traction Distribution" },
    { acronym: "IRTS", fullForm: "Indian Railway Traffic Service" },
    {
      acronym: "IRWCMS",
      fullForm: "Indian Railways Works Contract Management System",
    },
    { acronym: "IRWO", fullForm: "Indian Railway Welfare Organization" },
    { acronym: "ISMD", fullForm: "Infringing Standard Moving Dimensions" },
    { acronym: "ISRT", fullForm: "Inter Station Running Time" },
    { acronym: "ITC", fullForm: "Input Tax Credit" },
    { acronym: "IVRS", fullForm: "Interactive voice response system" },
  ],
  J: [
    { acronym: "JCM", fullForm: "Joint Consultative Machinery" },
    { acronym: "JPO", fullForm: "Joint Procedure Order" },
    { acronym: "JRRPF", fullForm: "Jagjivan Ram Railway Protection Force Academy" },
    { acronym: "JTBS", fullForm: "Jansadharan Ticket Booking Sewak" },
  ],
  K: [{ acronym: "KRCL", 
    fullForm: "Konkan Railway Corporation Limited",
    explanation: "To construct and operate railway lines, construct Road Over Bridges and rail line projects.",
    reference: "--"
  }],
  L: [
    { acronym: "LAP", fullForm: "Leave on Average Pay" },
    { acronym: "LAW", fullForm: "List of Approved Works" },
    { acronym: "LDCE", fullForm: "Limited Departmental Competitive Exam" },
    { acronym: "LGS", fullForm: "Second Class Coach (LHB)" },
    {
      acronym: "LGSLR",
      fullForm: "Second Class Cum Luggage and Brake Van (LHB)",
    },
    { acronym: "LHAP", fullForm: "Leave on Half Average Pay" },
    { acronym: "LHB", fullForm: "Linke Holfmann Busch" },
    { acronym: "LI", fullForm: "Loco Inspector" },
    {
      acronym: "LIMBS",
      fullForm: "Legal Information Management & Briefing System",
    },
    {
      acronym: "LRZAC",
      fullForm: "EOG AC Track Recording Car LHB Variant Coach",
    },
    {
      acronym: "LRDAC",
      fullForm: "Track Recording Staff Car LHB Variant Coach",
    },
    {
      acronym: "LSFTO",
      fullForm: "Liberalized Special Freight Train Operators",
    },
    { acronym: "LSS", fullForm: "Last Stop Signal" },
    { acronym: "LTC", fullForm: "Last Train Certificate" },
    { acronym: "LTC", fullForm: "Leave Travel Concession" },
    { acronym: "LTTC", fullForm: "Long Term Traffic Contact" },
    { acronym: "LSWP", fullForm: "Lumpsum Works Program" },
    { acronym: "LVCD", fullForm: "Last Vehicle Check Device" },
    { acronym: "LVI", fullForm: "Last Vehicle Indicator" },
    { acronym: "LWFAC", fullForm: "AC First Class Coach (LHB)" },
    { acronym: "LWACCN", fullForm: "AC 3 Tier Sleeper Coach (LHB)" },
    { acronym: "LWACCW", fullForm: "AC 2 Tier Sleeper Coach (LHB)" },
    { acronym: "LFCBAC", fullForm: "AC Hot Buffer Car (LHB)" },
    { acronym: "LWCB", fullForm: "Non-AC Hot Buffer Car (LHB)" },
    { acronym: "LWLRRM", fullForm: "Brake Luggage Cum Generator Car (LHB)" },
    { acronym: "LWFCZAC", fullForm: "AC Executive Chair Car (LHB)" },
    {
      acronym: "LWOGCARAC",
      fullForm: "EOG AC Data Acquisition and Analysis Car",
    },
    { acronym: "LWSCN", fullForm: "Non-AC 3 Tier Sleeper Coach (LHB)" },
    { acronym: "LWIS", fullForm: "Liberalized Wagon Investment Scheme" },
    { acronym: "LWR", fullForm: "Long Welded Rails" },
  ],
  M: [
    { acronym: "MACP", fullForm: "Modified Assured Career Progression" },
    { acronym: "MACL", fullForm: "Multiple Aspect Color Light" },
    { acronym: "MASA", fullForm: "Multiple Aspect Signalling Arrangement" },
    { acronym: "MCDO", fullForm: "Monthly Confidential Demi Official" },
    {
      acronym: "MDZTI",
      fullForm: "Multi Disciplinary Zonal Training Institute",
    },
    { acronym: "ME", fullForm: "Member Electrical" },
    { acronym: "MELE", fullForm: "Multiple Electric Light Engine" },
    { acronym: "MEMU", fullForm: "Mainline Electrical Multiple Unit" },
    { acronym: "MGR", fullForm: "Many Go Round" },
    { acronym: "MLRI", fullForm: "Multi Lamp Route Indicator" },
    { acronym: "MM", fullForm: "Member Mechanical" },
    { acronym: "MMTS", fullForm: "Multi Model Transport System" },
    { acronym: "MOBD", fullForm: "Member Operations & Business Development" },
    { acronym: "MOMA", fullForm: "Manually Operated Multiple Aspect" },
    { acronym: "MOR", fullForm: "Ministry of Railways" },
    { acronym: "MOSR", fullForm: "Minister of State for Railways" },
    { acronym: "MPS", fullForm: "Maximum Permissible Speed" },
    { acronym: "MRT", fullForm: "Minimum Running Time" },
    { acronym: "MRTS", fullForm: "Mass Rapid Transport System" },
    { acronym: "MRV", fullForm: "Medical Relief Van" },
    { acronym: "MRVC", 
      fullForm: "Mumbai Railway Vikas Corporation Limited", 
      explanation: "To plan & implement rail projects in the Mumbai Metropolitan Region.", 
      reference: "--" 
    },
    { acronym: "MSASS", fullForm: "Modified Semi Automatic Stop Signal" },
    { acronym: "MSS", fullForm: "Manual Stop Signal" },
    { acronym: "MSD", fullForm: "Minimum sighting Distance" },
    { acronym: "MSDAC", fullForm: "Multi Section Digital Axle Counter" },
    { acronym: "MTRC", fullForm: "Mobile Train Radio Communication" },
    { acronym: "MTI", fullForm: "Material Train Inspector" },
    { acronym: "MTRS", fullForm: "Member Traction Rolling Stock" },
  ],
  N: [
    { acronym: "NAIR", fullForm: "National Academy of Indian Railway" },
    { acronym: "NCDRC", fullForm: "National Consumer Dispute Redressal Commission" },
    { acronym: "NDMA", fullForm: "National Disaster Management Authority" },
    { acronym: "NDR", fullForm: "National Disaster Response Force" },
    { acronym: "NFIR", fullForm: "National Federation of Indian Railwaymen" },
    { acronym: "NHSRCL", fullForm: "National High Speed Rail Corporation of India Limited" },
    { acronym: "NLP", fullForm: "National Logistics Policy" },
    { acronym: "NMG", fullForm: "Newly Modified Goods" },
    { acronym: "NMS", fullForm: "Network Management System" },
    { acronym: "NPG", fullForm: "Network Planning Group" },
    { acronym: "NPS", fullForm: "New Pension System" },
    { acronym: "NPS", fullForm: "National Pension System" },
    { acronym: "NRP", fullForm: "National Rail Plan" },
    { acronym: "NRT", fullForm: "Normal Running Time" },
    { acronym: "NTES", fullForm: "National Train Enquiry System" },
    { acronym: "NTKM", fullForm: "Net Tonne Kilo Meter" },
  ],
  O: [
    { acronym: "OBC", fullForm: "Over Bulky Consignment" },
    { acronym: "OCMS", fullForm: "Online Computerized Monitoring System" },
    { acronym: "OCR", fullForm: "Optical Character Recognition" },
    { acronym: "OCV", 
      fullForm: "Other Coaching Vehicle",
      explanation: "These vehicles do not have a passenger carrying portion but are planned to be attached to coaching trains for providing other facilities. Saloons, inspection cars, medical cars, tourist cars, parcels & horse van, composite luggage Power Cars, Pantry Cars & brake van are some of the OCVs.",
      reference: "--"
    },
    { acronym: "ODC", fullForm: "Over Dimensional Consignment" },
    { acronym: "ODR", fullForm: "Oldest Date of Registration" },
    { acronym: "OFC", fullForm: "Optical Fibre Cable" },
    { acronym: "OHE", fullForm: "Over Head Equipment" },
    { acronym: "OLIC", fullForm: "Official Language Implementation Committee" },
    { acronym: "OM", fullForm: "Operating Manual" },
    { acronym: "OMRS", fullForm: "On Board Monitoring of Rolling Stock" },
    { acronym: "ONDC", fullForm: "Open Network for Digital Commerce" },
    { acronym: "OPS", fullForm: "Old Pension Scheme" },
    { acronym: "OOT", fullForm: "Out Of Turn" },
    { acronym: "OTL", fullForm: "One Time Lock" },
    { acronym: "OTOS", fullForm: "One Train Only System" },
    { acronym: "OYWS", fullForm: "Own Your Wagon Scheme" },
  ],
  P: [
    { acronym: "PAD", fullForm: "Pre Arrival Detention" },
    { acronym: "PAM", fullForm: "Punctuality Analysis & Monitoring" },
    { acronym: "PCC", fullForm: "Permissible Carrying Capacity" },
    { acronym: "PCCM", fullForm: "Principal Chief Commercial Manager" },
    { acronym: "PCDO", fullForm: "Periodical Confidential Demi Official" },
    { acronym: "PCDR", fullForm: "Personal Cash Declaration Register" },
    { acronym: "PCEE", fullForm: "Principal Chief Electrical Engineer" },
    { acronym: "PCE", fullForm: "Principal Chief Engineer" },
    { acronym: "PCEV", fullForm: "Percentage Charge on Excessive Value" },
    { acronym: "PCMD", fullForm: "Principal Chief Medical Director" },
    { acronym: "PCME", fullForm: "Principal Chief Mechanical Engineer" },
    { acronym: "PCMM", fullForm: "Principal Chief Materials Manager" },
    { acronym: "PCOM", fullForm: "Principal Chief Operations Manager" },
    { acronym: "PCPO", fullForm: "Principal Chief Personnel Officer" },
    { acronym: "PCSC", fullForm: "Principal Chief Security Commissioner" },
    { acronym: "PCSO", fullForm: "Principal Chief Safety Officer" },
    { acronym: "PCV", fullForm: "Passenger Carrying Vehicle" },
    { acronym: "PFRDA", fullForm: "Pension Fund Regulatory and Development Authority" },
    {
      acronym: "PCSTE",
      fullForm: "Principal Chief Signal and Telecommunication Engineer",
    },
    { acronym: "PCV", 
      fullForm: "Passenger Coaching Vehicle",
      explanation: "A vehicle in which whole or some portion is being utilized for carrying passengers.",
      reference: "--"
    },
    { acronym: "PCVO", fullForm: "Principal Chief Vigilance Officer" },
    { acronym: "PDD", fullForm: "Pre Departure Detention" },
    { acronym: "PDT", fullForm: "Pre Departure Time" },
    { acronym: "PEASD", fullForm: "Passenger Emergency Alarm Signal Device" },
    { acronym: "PED", fullForm: "Principal Executive Director" },
    { acronym: "PETS", fullForm: "Premilinary Engineering cum Traffic Survey" },
    { acronym: "PFA", fullForm: "Principal Financial Advisor" },
    { acronym: "PFT", fullForm: "Private Freight Terminals" },
    { acronym: "PFT", fullForm: "Portable Field Telephone" },
    { acronym: "PGC", fullForm: "Passenger Gaurd Course" },
    { acronym: "PGRM", fullForm: "Public Grievance Redressal Machinery" },
    { acronym: "PGS", fullForm: "Pilot Guard System" },
    { acronym: "PHS", fullForm: "Proceed Hand Signal" },
    { acronym: "PHOD", fullForm: "Principal Head of Department" },
    { acronym: "PIA", fullForm: "Project Influence Area" },
    { acronym: "PLCT", fullForm: "Paper Line Clear Ticket" },
    { acronym: "PLPM", fullForm: "Pay Level in Pay Matrix" },
    { acronym: "PME", fullForm: "Periodic Medical Examination" },
    { acronym: "PME", fullForm: "Periodical Monitoring Examination" },
    { acronym: "PME", fullForm: "Preventive Maintenance Examination" },
    { acronym: "PMS", fullForm: "Passenger Management System" },
    { acronym: "PNM", fullForm: "Permanent Negotiating Machinery" },
    { acronym: "PNR", fullForm: "Passenger Name record" },
    { acronym: "POET", fullForm: "Passenger Operated Enquiry Terminal" },
    { acronym: "POH", fullForm: "Periodical Over Hauling" },
    { acronym: "POL", fullForm: "Petroleum Oil Lubricants" },
    { acronym: "POMKA", fullForm: "Portable Medical Kit for Accidents" },
    { acronym: "POS", fullForm: "Point of Sale" },
    { acronym: "PPAN", fullForm: "Permanent Pension Account Number" },
    { acronym: "PPO", fullForm: "Pension Payment Order" },
    { acronym: "PQRS", fullForm: "Plasser Quick Relaying System" },
    { acronym: "PRCP", fullForm: "Post Retirement Complimentary Passes" },
    { acronym: "PREM", fullForm: "Participation of Railway Employees in Management" },
    { acronym: "PRO", fullForm: "Public Relations Officer" },
    { acronym: "PRS", fullForm: "Passenger Reservation System" },
    { acronym: "PSC", fullForm: "Pre Stressed Concrete Sleepers" },
    { acronym: "PSR", fullForm: "Permanent Speed Restrictions" },
    { acronym: "PSSA", fullForm: "Project Supervisors Services Agencies" },
    { acronym: "PTO", fullForm: "Preferential Traffic Order" },
    { acronym: "PTO", fullForm: "Previlege Ticket Order" },
    { acronym: "PTS", fullForm: "Preferential Time Schedule" },
    { acronym: "PTT", fullForm: "Public Time Table" },
    { acronym: "PTVM", fullForm: "Platform Ticket Vending Machine" },
    { acronym: "PVC", fullForm: "Price Variation Cause" },
    { acronym: "PVIS", fullForm: "Photographic Vehicle Identification System" },
    { acronym: "PWB", fullForm: "Parcel Way Bills" },
    { acronym: "PWB", fullForm: "Passenger Warning Board" },
    { acronym: "PWI", fullForm: "Permanent Way Inspector" },
    { acronym: "PWP", fullForm: "Preliminary Works Program" },
  ],
  Q: [{ acronym: "QCBS", fullForm: "Quality and Cost Based Selection" }],
  R: [
    { acronym: "RA", fullForm: "Inspection Carriage (Administration)" },
    { acronym: "RAS", fullForm: "Rake Allocation System" },
    { acronym: "RB", fullForm: "Inspection Carriage (Divisional Officers)" },
    { acronym: "RBPC", fullForm: "Round Trip Brake Power Certificate" },
    { acronym: "RM", fullForm: "Railway Motor Van" },
    { acronym: "RH", fullForm: "Railway Hospital Van" },
    { acronym: "RZ", fullForm: "Track Recorder Car" },
    { acronym: "RAC", fullForm: "Reservation Against Cancellation" },
    { acronym: "RARV", fullForm: "Road Accident Restoration Vehicles" },
    { acronym: "RBS", fullForm: "Rates Branch System" },
    { acronym: "RCIL", 
      fullForm: "RailTel Corporation of India Limited", 
      explanation: "To utilize the surplus telecom capacity and right of way available with the IR to build nationwide optical fibre cable based broadband telecom and multimedia network", 
      reference: "--" 
    },
    { acronym: "RCM", fullForm: "Reverse Charge Mechanism" },
    { acronym: "RCP", fullForm: "Residental Card Pass" },
    { acronym: "RCT", fullForm: "Railway Claims Tribunal" },
    { acronym: "RDM", fullForm: "Rescue Drive Mode" },
    {
      acronym: "RDSO",
      fullForm: "Research Designs and Standards Organisation",
    },
    { acronym: "RDW", fullForm: "Rail Dolly Works" },
    {
      acronym: "REMMLOT",
      fullForm: "Remote Monitoring and Management of Locomotives and Trains",
    },
    { acronym: "RESS", fullForm: "Railway Employee Self Service" },
    {
      acronym: "RELHS",
      fullForm: "Retired Employees Liberalized Health Scheme",
    },
    {
      acronym: "RETS",
      fullForm: "Reconnaissance Engineering cum Traffic Survey",
    },
    { acronym: "RFID", fullForm: "Radio Frequency Identification" },
    { acronym: "RFMS", fullForm: "Referential File Management System" },
    { acronym: "RIDE", fullForm: "Rail Infrastructure Development Corporation" },
    { acronym: "RITES", fullForm: "Rail India Technical and Economic Services Limited", explanation: "To design, establish, provide, operate, maintain and perform engineering, technical and consultancy services for development of projects/systems of all types and descriptions pertaining to Railways and other Sectors/Industries in India and outside India.", reference: "--" },
    { acronym: "RIU", fullForm: "Remote Interface Unit" },
    { acronym: "RKMS", fullForm: "Route Kilometers" },
    { acronym: "RLDA", 
      fullForm: "Railway Land Development Authority",
      explanation: "To develop vacant railway land for commercial use for the purpose of generating revenue by non-tariff measures for IR.",
      reference: "--"
    },
    { acronym: "RLT", fullForm: "Railway Labour Tribunal" },
    { acronym: "RMP", fullForm: "Registered Medical Practitioner" },
    { acronym: "RMS", fullForm: "Rake Management System" },
    { acronym: "ROB", fullForm: "Rail Over Bridge" },
    { acronym: "ROH", fullForm: "Routine Over Hauling" },
    { acronym: "RORO", fullForm: "Roll On Roll Off" },
    { acronym: "ROSHAN", fullForm: "Rolling Stock Health Analyst" },
    { acronym: "RPF", fullForm: "Railway Protection Force" },
    { acronym: "RRB", fullForm: "Railway Recruitment Board" },
    { acronym: "RRC", fullForm: "Railway Recruitment Cell" },
    { acronym: "RRCB", fullForm: "Railway Recruitment Control Board" },
    { acronym: "RRI", fullForm: "Route Relay Interlocking" },
    { acronym: "RRSK", fullForm: "Rashtriya Rail Sanraksha Kosh" },
    { acronym: "RRT", fullForm: "Railway Rates Tribunal" },
    { acronym: "RSC", fullForm: "Rolling Stock Controller" },
    { acronym: "RSC", fullForm: "Railway Staff College" },
    { acronym: "RSHC", fullForm: "RPF Security Helpline" },
    { acronym: "RSP", fullForm: "Rolling Stock Performance" },
    { acronym: "RSPB", fullForm: "Railway Safety Promotion Board" },
    { acronym: "RSIS", fullForm: "Rolling Stock Inspection System" },
    { acronym: "RSMS", fullForm: "RPF Security Management System" },
    { acronym: "RSS", fullForm: "Reception Stop Signal" },
    { acronym: "RTIS", fullForm: "Realtime Train Information System" },
    { acronym: "RTRC", fullForm: "Railway Testing & Research Centre" },
    { acronym: "RTT", fullForm: "Round Trip Tariff" },
    { acronym: "RUB", fullForm: "Rail Under Bridge" },
    { acronym: "RVNL", 
      fullForm: "Rail Vikas Nigam Limited",
      explanation: "To create and augment the capacity of rail infrastructure. To mobilize resources mainly through multilateral/bilateral funding agencies and also through domestic market for successful implementation of projects.",
      reference: "--"
    },
  ],
  S: [
    {
      acronym: "SAMPRATI",
      fullForm:
        "Status Alerts in Monitoring Projects Related Actions & Targets Importance",
    },
    { acronym: "SASS", fullForm: "Semi Automatic Stop Signal" },
    {
      acronym: "SATSANG",
      fullForm: "Software Aided Train Scheduling And Network Governance",
    },
    { acronym: "SB", fullForm: "Stop Board" },
    { acronym: "SBCM", fullForm: "Shoulder Blast Clearing Machine" },
    { acronym: "SBU", fullForm: "Signal & Brake Unit" },
    { acronym: "SCO", fullForm: "Sectional Caution Order" },
    { acronym: "SCRA", fullForm: "Special Class Railway Apprentices" },
    { acronym: "SDGM", fullForm: "Senior Deputy General Manager" },
    { acronym: "SDIR", fullForm: "Stop Dead If Required" },
    {
      acronym: "SFOORTI",
      fullForm:
        "Smart Freight Operation Optimisation and Real Time Information",
    },
    { acronym: "SG", fullForm: "Self Generated" },
    { acronym: "SI", fullForm: "Special Instructions" },
    { acronym: "SI", fullForm: "Speed Indicator" },
    { acronym: "SIMRAN", fullForm: "Satellite Imaging for Rail Navigation" },
    { acronym: "SIMS", fullForm: "Safety Information Management System." },
    { acronym: "SIP", fullForm: "Signal Interlocking Plan" },
    { acronym: "SLB", fullForm: "Shunting Limit Board" },
    { acronym: "SLI", fullForm: "Senior Loco Inspector" },
    { acronym: "SLO", fullForm: "Specific Loading Order" },
    { acronym: "SLR", fullForm: "Second Class Luggage & Brake Van" },
    { acronym: "SLRD", fullForm: "Second Class Luggage, Brake Van & Disabled" },
    { acronym: "SM", fullForm: "Station Master" },
    { acronym: "SMART", fullForm: "Specially Modified Asthetic Refreshing Travel" },
    {
      acronym: "SMARTS",
      fullForm: "Singular Modular Advance Railway Ticketing System",
    },
    {
      acronym: "SMOCIP",
      fullForm: "Station Master Operation Cum Identification Panel",
    },
    { acronym: "SOB", fullForm: "Standing Order Book" },
    { acronym: "SOD", fullForm: "Schedule Of Dimensions" },
    { acronym: "SOL", fullForm: "Signal Over Lap" },
    { acronym: "SOP", fullForm: "Schedule Off Powers" },
    { acronym: "SPAD", fullForm: "Signal Passing At Danger" },
    {
      acronym: "SPARME",
      fullForm: "Self Profelled Accident Relief Medical Equipment",
    },
    {
      acronym: "SPARROW",
      fullForm: "Smart Performance Appraisal Report Recording Online Window",
    },
    { acronym: "SPART", fullForm: "Self Profelled Accident Relief Trains" },
    {
      acronym: "SPASHT",
      fullForm: "Safe Practices Avoiding Shortcut Methods in Train Operations",
    },
    { acronym: "SPI", fullForm: "Shunting Permitted Indicator" },
    { acronym: "SPO", fullForm: "Senior Personnel Officer" },
    { acronym: "SPT", fullForm: "Signal Post Telephone" },
    { acronym: "SPTM", fullForm: "Self Printing Ticket Machines" },
    {
      acronym: "SPURT",
      fullForm: "Self Profelled Ultrasonic Rail Testing Car",
    },
    { acronym: "SR", fullForm: "Subsidiary Rules" },
    { acronym: "SRIJAN", fullForm: "Station Rejuvenation Initiative through Joint Action" },
    { acronym: "SRSB", fullForm: "Swachh Rail Swachh Bharat" },
    { acronym: "SRSF", fullForm: "Special Railway Safety Fund" },
    {
      acronym: "SSBPAC",
      fullForm: "Solid State Block Proving by Axle Counter",
    },
    { acronym: "SSD", fullForm: "Speed Sensing Device" },
    { acronym: "SSDAC", fullForm: "Single section Digital axle counter" },
    { acronym: "SSE", fullForm: "Senior Section Engineer" },
    { acronym: "SSI", fullForm: "Solid State Interlocking" },
    { acronym: "SSP", fullForm: "Sub Sectioning & Paralleling Post" },
    { acronym: "STM", fullForm: "Senior Transportation Manager" },
    { acronym: "STR", fullForm: "Safety To Run" },
    { acronym: "STRI", fullForm: "Stensile Type Route Indication" },
    { acronym: "STS", fullForm: "Station to Station Rates" },
    { acronym: "SRSF", fullForm: "Special Railway Safety Fund" },
    { acronym: "STBA", fullForm: "Station Ticket Booking Agent" },
    { acronym: "SWR", fullForm: "Station Working Rule" },
    { acronym: "SWRD", fullForm: "Station Working Rule Diagram" },
    { acronym: "SYLR", fullForm: "Second Class Ladies, Luggage & Brake Van" },
  ],
  T: [
    { acronym: "TACL", fullForm: "Two Aspect Colour Light" },
    {
      acronym: "TACLS",
      fullForm: "Train Actuated Control Level Crossing System",
    },
    { acronym: "TALQ", fullForm: "Two Aspect Lower Quadrant" },
    { acronym: "TAMS", fullForm: "Traffic Accounts Management System" },
    { acronym: "TASA", fullForm: "Two Aspect Signalling Arrangement" },
    { acronym: "TAST", fullForm: "Two Aspect Signalling Territory" },
    { acronym: "TAWD", fullForm: "Train Actuated Warning Device" },
    { acronym: "TBR", fullForm: "Through Ballast Renewal" },
    { acronym: "TBTR", fullForm: "Through Bridge Timber Renewal" },
    { acronym: "TCAS", fullForm: "Train Collision Avoidance System" },
    { acronym: "TCC", fullForm: "Travelling Cash Chest" },
    { acronym: "TCMS", fullForm: "Train Control & Management System" },
    { acronym: "TDC", fullForm: "Tentative Date of Cancellation" },
    { acronym: "TDMS", fullForm: "Track Distribution Management System" },
    { acronym: "TEFD", fullForm: "Traditional Empty Flow Direction" },
    { acronym: "TFW", fullForm: "Traffic Facility Works" },
    { acronym: "TG", fullForm: "Tank for LPG" },
    { acronym: "TG", fullForm: "Termination for Goods Train" },
    { acronym: "TIC", fullForm: "Total Interruption of Communication" },
    { acronym: "TIEL", fullForm: "Terminal Incentive cum Engine on Load" },
    { acronym: "TIN", fullForm: "Track Identification Number" },
    { acronym: "TLBI", fullForm: "Token Less Block Instrument" },
    { acronym: "TLC", fullForm: "Traction Loco Controller" },
    { acronym: "TK", fullForm: "Tank for Kerosene" },
    { acronym: "TMC", fullForm: "Terminal Management Company" },
    { acronym: "TMS", fullForm: "Track Management System" },
    { acronym: "TMS", fullForm: "Terminal Management System" },
    { acronym: "TP", fullForm: "Tank for Petroleum" },
    { acronym: "TP", fullForm: "Termination for Passenger Train" },
    { acronym: "TPC", fullForm: "Traction Power Controller" },
    { acronym: "TPWS", fullForm: "Train Protection & Warning System" },
    { acronym: "TRD", fullForm: "Traction Distribution" },
    { acronym: "TRR", fullForm: "Through Rail Renewal" },
    { acronym: "TSL", fullForm: "Temporary Single Line" },
    { acronym: "TSR", fullForm: "Train Signal Register" },
    { acronym: "TSR", fullForm: "Temporary Speed Restriction" },
    { acronym: "TSTS", fullForm: "Train Staff Ticket System" },
    { acronym: "TTC", fullForm: "Time Table Controller" },
    { acronym: "TTM", fullForm: "Track Tamping Machine" },
    { acronym: "TTR", fullForm: "Track Turnout Renewal" },
    { acronym: "TVU", fullForm: "Train Vehicle Unit" },
    { acronym: "TW", fullForm: "Tank for Water" },
    { acronym: "TWI", fullForm: "Temporary Working Instructions" },
    { acronym: "TWR", fullForm: "Through Weld Renewal" },
    { acronym: "TWS", fullForm: "Thick Web Switches" },
    { acronym: "TXR", fullForm: "Train Examiner" },
  ],
  U: [
    { acronym: "UDAY", fullForm: "Utkrist Double Decker Air Condition Yatri Express" },
    { acronym: "UFSBI", fullForm: "Universal Fail Safe Block Interface" },
    { acronym: "ULIP", fullForm: "Unified Logistics Interface Platform" },
    { acronym: "UMID", fullForm: "Unique Medical Identity Card" },
    { acronym: "UMLCG", fullForm: "Unmanned Level Crossings Gate" },
    { acronym: "UPI", fullForm: "Unified Payments Interface" },
    { acronym: "UPS", fullForm: "Unified Pension Scheme" },
    { acronym: "USFD", fullForm: "Ultra Sonic Flaw Detection" },
    { acronym: "UTS", fullForm: "Unreserved Ticketing System" },
  ],
  V: [
    { acronym: "VCB", fullForm: "Vacuum Circuit Braker" },
    { acronym: "VCC", fullForm: "Vacuum Continuity Certificate" },
    { acronym: "VCD", fullForm: "Vigilance Control Device" },
    { acronym: "VDU", fullForm: "Visual Display Unit" },
    { acronym: "VG", fullForm: "Vehicle Guidance" },
    { acronym: "VHF", fullForm: "Very High Frequency" },
    { acronym: "VTO", fullForm: "Visibility Test Object" },
    { acronym: "VTP", fullForm: "Visibility Test Post" },
  ],
  W: [
    { acronym: "WCA", fullForm: "Workmen Compensation Act" },
    { acronym: "WCM", fullForm: "Wheel Condition Monitor" },
    { acronym: "WFCZ", fullForm: "Vestibule First Class Chair Car" },
    {
      acronym: "WGSCZ",
      fullForm: "Vestibule Self-Generated Second Class Chair Car",
    },
    {
      acronym: "WGSCZAC",
      fullForm: "Vestibule Self-Generated Second Class AC Chair Car",
    },
    { acronym: "WGACCN", fullForm: "Vestibule Self-Generated AC Three Tier" },
    { acronym: "WGACCW", fullForm: "Vestibule Self-Generated AC Two Tier" },
    { acronym: "WGFCWAC", fullForm: "Vestibule Self-Generated First Class AC" },
    {
      acronym: "WGSCNLR",
      fullForm:
        "Vestibule Self-Generated Second Class Three Tier Sleeper Luggage",
    },
    { acronym: "WFDD", fullForm: "Wheel Flat Detection Device" },
    { acronym: "WILD", fullForm: "Wheel Impact Load Detection" },
    { acronym: "WRIIL", fullForm: "Work Related Illness and Injury Leave" },
    { acronym: "WTR", fullForm: "Wagon Turn Round" },
    { acronym: "WTT", fullForm: "Working Time Table" },
    { acronym: "WWB", fullForm: "Wagon Way Bill" },
  ],
  Y: [
    { acronym: "YM", fullForm: "Yard Master" },
    { acronym: "YMS", fullForm: "Yard Management System" },
    { acronym: "YTSK", fullForm: "Yatri Ticket Suvidha Kendra" },
  ],
  Z: [{ acronym: "ZULU", fullForm: "Zulu Time (UTC)" },
    { acronym: "ZRTI", fullForm: "Zonal Railway Training Institute" },
    { acronym: "ZRUCC", fullForm: "Zonal Railway User Consultative Committee" },
  ],
};
