
export const bellCodes = [
  {
    id: 1,
    code: "0",
    indication: "Call attention or attend telephone",
    signalled: "One stroke or beat",
    acknowledged: "One stroke or beat",
  },
  {
    id: 2,
    code: "00",
    indication: "Is line clear or line clear enquiry",
    signalled: "Two",
    acknowledged: "Two",
  },
  {
    id: 3,
    code: "000",
    indication: "Train entering block section",
    signalled: "Three",
    acknowledged: "Three",
  },
  {
    id: 4,
    code: "0000",
    indication: "(A)Train out of block section (B)Obstruction removed",
    signalled: "Four",
    acknowledged: "Four",
  },
  {
    id: 5,
    code: "00000",
    indication: "(A)Cancel last signal (B)Signal given in error",
    signalled: "Five",
    acknowledged: "Five",
  },
  {
    id: 6,
    code: "000000",
    indication: "Obstruction danger signal (general)",
    signalled: "Six",
    acknowledged: "Six",
  },
  {
    id: 7,
    code: "000000 _ 0",
    indication: "Stop and examine train",
    signalled: "Six pause one",
    acknowledged: "Six pause one",
  },
  {
    id: 8,
    code: "000000 _ 00",
    indication: "Train passed without tail lamp or tail board",
    signalled: "Six pause two",
    acknowledged: "Six pause two",
  },
  {
    id: 9,
    code: "000000 _ 000",
    indication: "Train divided",
    signalled: "Six pause three",
    acknowledged: "Six pause three",
  },
  {
    id: 10,
    code: "000000 _ 0000",
    indication: "Vehicles running away in wrong direction on double line or into the block section on single line",
    signalled: "Six pause four",
    acknowledged: "Six pause four",
  },
  {
    id: 11,
    code: "000000 _ 00000",
    indication: "Vehicles running away in right direction on double line",
    signalled: "Six pause five",
    acknowledged: "Six pause five",
  },
  {
    id: 12,
    code: "0000000000000000",
    indication: "Testing",
    signalled: "Sixteen",
    acknowledged: "Sixteen",
  },
]